# The port number for the proxy service. The proxied OpenAI API endpoint will be: http://localhost:3700/v1/chat/completions
port = 3700

# If you are a poe subscriber, you can find your API key on the poe official website. You must be a poe subscriber.如果你是poe订阅者，你可以在poe官网找到API_key,你必须是poe订阅者。
tokens = [""]

# Custom API Access Key.自定义接口访问密钥
accessTokens = ["sk-R6phF8lDbv4oFHdaEN8UFeD5569d4b248aBb87F16b597479"]

# The proxy that will be used to connect to poe.com. Leave it blank if you do not use a proxy
proxy = ""

# The gateway url for the Python backend of poe-api.
# Note that if you use docker this value should be changed into: http://external:5100（docker启动请改成：http://external:5100）
gateway = "http://localhost:5100"

# The gateway port for the Python backend of poe-api.
# Must be the same as the port indicated in the `gateway` above.
gateway-port = 5100


# Use leading prompts to indicate roles if enabled. You'd better disable it if you are using tools like https://github.com/TheR1D/shell_gpt
# 0:disable, 1:enable, 2:auto detect
# Example:
# ||>User:
# Hello!
# ||Assistant:
# Hello! How can I assist you today?
simulate-roles = 2

# Rate limit. Default to 60 api calls per token in 1 minute
rate-limit = 60

# Cool down of seconds. One same token cannot be used more than once in n seconds
cool-down = 3

# Timeout of seconds per response chunk
# This timeout will now reset every time a chunk is received
# so there's no need for a very large value to compensate for a very long reply
timeout = 180
# Timeout for poe-api, usually it should be smaller than timeout
api-timeout = 170


# The bot name map to use from poe.
[bot]
"gpt-3.5-turbo-16k" = "ChatGPT-16k"
"gpt-3.5-turbo" = "ChatGPT-16k"
"gpt-4" = "GPT-4"
"gpt-4o" = "GPT-4o"
"gpt-4-vision-preview" = "GPT-4-128k"
"gpt-4-turbo-preview" = "Claude-3-Opus"
"Gemini-1.5-Pro"="Gemini-1.5-Pro"
"Gemini-1.5-Pro-128k"="Gemini-1.5-Pro-128k"
"Gemini-1.5-Pro-1M"="Gemini-1.5-Pro-1M"
"DALL-E-3"="DALL-E-3"
"StableDiffusionXL"="StableDiffusionXL"
